CReATE TABLE [CUSTOMER] (
	CustomerID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newsequentialid(),
  	CustomerName nvarchar(255)
)

CReATE TABLE [MERCHANT] (
	MerchantID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newsequentialid(),
  	MerchantName nvarchar(255)
)

CREATE TABLE [TRANSACTIONS] (
    TransactionID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newsequentialid(),
  	CustomerID UNIQUEIDENTIFIER NOT NULL,
  	MerchantID UNIQUEIDENTIFIER NOT NULL,
    TransactionDate DATETIME NOT NULL,
    IsSuccessful Bit NOT NULL,
    CONSTRAINT fk_transactions_customer foreign key (CustomerId) REFERENCES Customer(CustomerID),
  	CONSTRAINT fk_transactions_merchant FOREIGN KEY (MerchantId) REFERENCES Merchant(MerchantID),
);

SELECT CUSTOMER.CustomerName, MERCHANT.MerchantName,
TRANSACTIONS.TransactionDate, TRANSACTIONS.IsSuccessful FROM TRANSACTIONS LEFT JOIN CUSTOMER
ON CUSTOMER.CustomerID = TRANSACTIONS.CustomerID
LEFT JOIN MERCHANT
ON MERCHANT.MerchantID = TRANSACTIONS.MerchantID;
GO

-- If we want to use a view
-- CREATE VIEW [TRANSACTION_VIEW] AS
-- SELECT CUSTOMER.CustomerName, MERCHANT.MerchantName,
-- TRANSACTIONS.TransactionDate, TRANSACTIONS.IsSuccessful FROM TRANSACTIONS LEFT JOIN CUSTOMER
-- ON CUSTOMER.CustomerID = TRANSACTIONS.CustomerID
-- LEFT JOIN MERCHANT
-- ON MERCHANT.MerchantID = TRANSACTIONS.MerchantID;
-- GO

-- SELECT * FROM [TRANSACTION_VIEW]; 
